backend:
  name: github
  repo: ghedd/tlj-blog

media_folder: static/assets
public_folder: assets

collections:
  - label: Blog
    name: blog
    folder: "src/_data/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      # - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { label: "Image", name: "image", widget: image }
      - { name: body, label: Body, widget: markdown }
  - label: Pages
    name: pages
    files:
      - label: About Page
        name: "about"
        file: "src/_data/pages/about.md"
        fields:
          - { label: Image, name: image, widget: image }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
